version: "3.8"
services:
  timeline:
    depends_on:
      - postgres
    build: .
    restart: on-failure
    ports:
      - 8000:8080
  postgres:
    image: postgres:16.1-alpine
    restart: unless-stopped
    environment:
      #TODO Vault OR env_file
      POSTGRES_DB: "timelinedb"
      POSTGRES_USER: "timelineusr"
      POSTGRES_PASSWORD: "timelinepwd"
    ports:
      - "5433:5432"