spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/timelinedb
    # TODO: Vault or env
    username: timelineusr
    password: timelinepwd
  jpa:
    # Enable SQL logging
    #show-sql: true
    # Format the SQL statements for better readability (optional)
    #properties:
    #  hibernate:
    #    format_sql: true
  liquibase:
    change-log: classpath:db/changelog.xml